-- Auto-generated B2.18: VoiceBlock spec table (64 bytes) from Service Manual mapping JSON
local M = {}
M.items = {
  {index=0, pp=0x40, schema_key="voice.name[0]", label="VOICE NAME char 1", range="ASCII 0..127", status="planned", bits=nil},
  {index=1, pp=0x41, schema_key="voice.name[1]", label="VOICE NAME char 2", range="ASCII 0..127", status="planned", bits=nil},
  {index=2, pp=0x42, schema_key="voice.name[2]", label="VOICE NAME char 3", range="ASCII 0..127", status="planned", bits=nil},
  {index=3, pp=0x43, schema_key="voice.name[3]", label="VOICE NAME char 4", range="ASCII 0..127", status="planned", bits=nil},
  {index=4, pp=0x44, schema_key="voice.name[4]", label="VOICE NAME char 5", range="ASCII 0..127", status="planned", bits=nil},
  {index=5, pp=0x45, schema_key="voice.name[5]", label="VOICE NAME char 6", range="ASCII 0..127", status="planned", bits=nil},
  {index=6, pp=0x46, schema_key="voice.name[6]", label="VOICE NAME char 7", range="ASCII 0..127", status="planned", bits=nil},
  {index=7, pp=0x47, schema_key="voice.user_code", label="USER'S CODE", range="0..255", status="planned", bits=nil},
  {index=8, pp=0x48, schema_key="voice.lfo_speed", label="LFO SPEED", range="0..127 (Max)", status="implemented", bits=nil},
  {index=9, pp=0x49, schema_key="voice.lfo_load_amd", label="LFO LOAD ENABLE + AMD", range="enable:0/1, amd:0..127", status="implemented", bits={["enable"]={7,7},["amd"]={6,0}}},
  {index=10, pp=0x4A, schema_key="voice.lfo_sync_pmd", label="LFO SYNC + PMD", range="sync:0/1, pmd:0..127", status="implemented", bits={["sync"]={7,7},["pmd"]={6,0}}},
  {index=11, pp=0x4B, schema_key="voice.enable_ops", label="ENABLE OPERATOR", range="bitmask OP1..OP4", status="implemented", bits={["mask"]={6,3}}},
  {index=12, pp=0x4C, schema_key="voice.algorithm_feedback", label="ALGORITHM + FEEDBACK", range="algo:0..7, fb:0..6", status="implemented", bits={["feedback"]={5,3},["algorithm"]={2,0}}},
  {index=13, pp=0x4D, schema_key="voice.mod_sensitivity", label="AMPLITUDE/PITCH MOD SENS", range="AMS:0..3, PMS:0..7", status="implemented", bits={["pms"]={5,3},["ams"]={1,0}}},
  {index=14, pp=0x4E, schema_key="voice.lfo_wave", label="LFO WAVEFORM", range="0..3", status="implemented", bits={["wave"]={6,5}}},
  {index=15, pp=0x4F, schema_key="voice.transpose", label="TRANSPOSE", range="0..127 or -25..+25 (2's comp)", status="implemented", bits=nil},
  {index=16, pp=0x50, schema_key="op1.volume", label="TOTAL LEVEL (TL)", range="0..127 (0=Max level)", status="implemented", bits=nil},
  {index=17, pp=0x51, schema_key="op1.level_velocity", label="KEYBOARD SCALING (LEVEL) TYPE + VELOCITY SENS", range="type bit + 0..7", status="implemented", bits=nil},
  {index=18, pp=0x52, schema_key="op1.level_depth_adjust", label="KEYBOARD SCALING (LEVEL) DEPTH + ADJUST", range="depth:0..15, adjust:0..15", status="implemented", bits=nil},
  {index=19, pp=0x53, schema_key="op1.detune_freq", label="DETUNE + FREQUENCY", range="detune type bit + fine/coarse", status="implemented", bits=nil},
  {index=20, pp=0x54, schema_key="op1.rate_depth_attack", label="KEYBOARD SCALING (RATE) DEPTH + ATTACK RATE", range="rate_depth:0..3, attack:0..31", status="implemented", bits=nil},
  {index=21, pp=0x55, schema_key="op1.carrier_flag_decay1", label="MODULATOR/CARRIER FLAG + DECAY1", range="flag:0/1, av:0..3, d1r:0..31", status="implemented", bits=nil},
  {index=22, pp=0x56, schema_key="op1.multiple_decay2", label="INHARMONIC FREQ (MUL) + DECAY2", range="mul:0..3, d2r:0..31", status="implemented", bits=nil},
  {index=23, pp=0x57, schema_key="op1.sustain_release", label="SUSTAIN LEVEL + RELEASE RATE", range="sl:0..15, rr:0..15", status="implemented", bits=nil},
  {index=24, pp=0x58, schema_key="op2.volume", label="TOTAL LEVEL (TL)", range="0..127 (0=Max level)", status="implemented", bits=nil},
  {index=25, pp=0x59, schema_key="op2.level_velocity", label="KEYBOARD SCALING (LEVEL) TYPE + VELOCITY SENS", range="type bit + 0..7", status="implemented", bits=nil},
  {index=26, pp=0x5A, schema_key="op2.level_depth_adjust", label="KEYBOARD SCALING (LEVEL) DEPTH + ADJUST", range="depth:0..15, adjust:0..15", status="implemented", bits=nil},
  {index=27, pp=0x5B, schema_key="op2.detune_freq", label="DETUNE + FREQUENCY", range="detune type bit + fine/coarse", status="implemented", bits=nil},
  {index=28, pp=0x5C, schema_key="op2.rate_depth_attack", label="KEYBOARD SCALING (RATE) DEPTH + ATTACK RATE", range="rate_depth:0..3, attack:0..31", status="implemented", bits=nil},
  {index=29, pp=0x5D, schema_key="op2.carrier_flag_decay1", label="MODULATOR/CARRIER FLAG + DECAY1", range="flag:0/1, av:0..3, d1r:0..31", status="implemented", bits=nil},
  {index=30, pp=0x5E, schema_key="op2.multiple_decay2", label="INHARMONIC FREQ (MUL) + DECAY2", range="mul:0..3, d2r:0..31", status="implemented", bits=nil},
  {index=31, pp=0x5F, schema_key="op2.sustain_release", label="SUSTAIN LEVEL + RELEASE RATE", range="sl:0..15, rr:0..15", status="implemented", bits=nil},
  {index=32, pp=0x60, schema_key="op3.volume", label="TOTAL LEVEL (TL)", range="0..127 (0=Max level)", status="implemented", bits=nil},
  {index=33, pp=0x61, schema_key="op3.level_velocity", label="KEYBOARD SCALING (LEVEL) TYPE + VELOCITY SENS", range="type bit + 0..7", status="implemented", bits=nil},
  {index=34, pp=0x62, schema_key="op3.level_depth_adjust", label="KEYBOARD SCALING (LEVEL) DEPTH + ADJUST", range="depth:0..15, adjust:0..15", status="implemented", bits=nil},
  {index=35, pp=0x63, schema_key="op3.detune_freq", label="DETUNE + FREQUENCY", range="detune type bit + fine/coarse", status="implemented", bits=nil},
  {index=36, pp=0x64, schema_key="op3.rate_depth_attack", label="KEYBOARD SCALING (RATE) DEPTH + ATTACK RATE", range="rate_depth:0..3, attack:0..31", status="implemented", bits=nil},
  {index=37, pp=0x65, schema_key="op3.carrier_flag_decay1", label="MODULATOR/CARRIER FLAG + DECAY1", range="flag:0/1, av:0..3, d1r:0..31", status="implemented", bits=nil},
  {index=38, pp=0x66, schema_key="op3.multiple_decay2", label="INHARMONIC FREQ (MUL) + DECAY2", range="mul:0..3, d2r:0..31", status="implemented", bits=nil},
  {index=39, pp=0x67, schema_key="op3.sustain_release", label="SUSTAIN LEVEL + RELEASE RATE", range="sl:0..15, rr:0..15", status="implemented", bits=nil},
  {index=40, pp=0x68, schema_key="op4.volume", label="TOTAL LEVEL (TL)", range="0..127 (0=Max level)", status="implemented", bits=nil},
  {index=41, pp=0x69, schema_key="op4.level_velocity", label="KEYBOARD SCALING (LEVEL) TYPE + VELOCITY SENS", range="type bit + 0..7", status="implemented", bits=nil},
  {index=42, pp=0x6A, schema_key="op4.level_depth_adjust", label="KEYBOARD SCALING (LEVEL) DEPTH + ADJUST", range="depth:0..15, adjust:0..15", status="implemented", bits=nil},
  {index=43, pp=0x6B, schema_key="op4.detune_freq", label="DETUNE + FREQUENCY", range="detune type bit + fine/coarse", status="implemented", bits=nil},
  {index=44, pp=0x6C, schema_key="op4.rate_depth_attack", label="KEYBOARD SCALING (RATE) DEPTH + ATTACK RATE", range="rate_depth:0..3, attack:0..31", status="implemented", bits=nil},
  {index=45, pp=0x6D, schema_key="op4.carrier_flag_decay1", label="MODULATOR/CARRIER FLAG + DECAY1", range="flag:0/1, av:0..3, d1r:0..31", status="implemented", bits=nil},
  {index=46, pp=0x6E, schema_key="op4.multiple_decay2", label="INHARMONIC FREQ (MUL) + DECAY2", range="mul:0..3, d2r:0..31", status="implemented", bits=nil},
  {index=47, pp=0x6F, schema_key="op4.sustain_release", label="SUSTAIN LEVEL + RELEASE RATE", range="sl:0..15, rr:0..15", status="implemented", bits=nil},
  {index=48, pp=0x70, schema_key="voice.reserved_70", label="RESERVED/UNKNOWN (0x70)", range="0..255", status="reserved", bits=nil},
  {index=49, pp=0x71, schema_key="voice.reserved_71", label="RESERVED/UNKNOWN (0x71)", range="0..255", status="reserved", bits=nil},
  {index=50, pp=0x72, schema_key="voice.reserved_72", label="RESERVED/UNKNOWN (0x72)", range="0..255", status="reserved", bits=nil},
  {index=51, pp=0x73, schema_key="voice.reserved_73", label="RESERVED/UNKNOWN (0x73)", range="0..255", status="reserved", bits=nil},
  {index=52, pp=0x74, schema_key="voice.reserved_74", label="RESERVED/UNKNOWN (0x74)", range="0..255", status="reserved", bits=nil},
  {index=53, pp=0x75, schema_key="voice.reserved_75", label="RESERVED/UNKNOWN (0x75)", range="0..255", status="reserved", bits=nil},
  {index=54, pp=0x76, schema_key="voice.reserved_76", label="RESERVED/UNKNOWN (0x76)", range="0..255", status="reserved", bits=nil},
  {index=55, pp=0x77, schema_key="voice.reserved_77", label="RESERVED/UNKNOWN (0x77)", range="0..255", status="reserved", bits=nil},
  {index=56, pp=0x78, schema_key="voice.reserved_78", label="RESERVED/UNKNOWN (0x78)", range="0..255", status="reserved", bits=nil},
  {index=57, pp=0x79, schema_key="voice.reserved_79", label="RESERVED/UNKNOWN (0x79)", range="0..255", status="reserved", bits=nil},
  {index=58, pp=0x7A, schema_key="voice.poly_porta", label="POLY/MONO + PORTAMENTO SPEED", range="poly:0/1, porta:0..127", status="implemented", bits={["poly"]={7,7},["porta"]={6,0}}},
  {index=59, pp=0x7B, schema_key="voice.controller_pitchbend", label="INPUT CONTROLLER + PITCHBEND RANGE", range="ctrl:0..4, pb:0..12", status="implemented", bits={["ctrl"]={6,4},["pb"]={3,0}}},
  {index=60, pp=0x7C, schema_key="voice.breath_sensitivity", label="BREATH SENSITIVITY", range="0..12? (manual shows 0..12 in bottom table area)", status="planned", bits=nil},
  {index=61, pp=0x7D, schema_key="voice.reserved_7D", label="RESERVED 0x7D", range="0", status="planned", bits=nil},
  {index=62, pp=0x7E, schema_key="voice.reserved_7E", label="RESERVED 0x7E", range="0", status="planned", bits=nil},
  {index=63, pp=0x7F, schema_key="voice.reserved_7F", label="RESERVED 0x7F", range="0", status="planned", bits=nil},
}
return M
